# Generated by Django 5.2 on 2025-05-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie_Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_fmat", models.CharField(max_length=3)),
                ("storage_link", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=50)),
                ("director", models.CharField(max_length=50)),
                ("genre", models.CharField(max_length=20)),
                ("release_date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review_Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.CharField(max_length=255)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, max_digits=2, null=True),
                ),
                ("rate_date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User_Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=50)),
                ("phone", models.IntegerField(null=True)),
                ("email", models.CharField(max_length=100)),
            ],
        ),
    ]
